### ISSUE TITLE
Flexible hash engine

### ISSUE THREAD

**Issue by laurentsimon** [sigstore/model-transparency#140]
We may want to:
1. Support hashing for GPU
2. Have an API that allows passing in a custom hash engine. Callers can take advantage of their own hardware to speed up hashing. Alternatively, allow passing the hash as input

**Comment by mihaimaruseac** [comment]
I think 2 is done via #188 and GPU support should not be as part of v1 release. Ok to close and open a new feature request for GPU hashing? Or leave this as is but just exclude from milestone?

**Comment by laurentsimon** [comment]
LGTM

**Comment by mihaimaruseac** [comment]
Made #201 for the GPU case and can close this now
