### ISSUE TITLE
Cleanup BaseResult

### ISSUE THREAD

**Issue by laurentsimon** [sigstore/model-transparency#174]
See comment https://github.com/sigstore/model-transparency/blob/laurentsimon-patch-1/model_signing/model.py#L45

We need to provide a verbose parameter. When verbose is disabled, errors will be generic and not leak information (paths, etc).
We also need to expose this in the CLI and the main model.verify / model.sign API.

**Comment by mihaimaruseac** [comment]
I think we can close this since we no longer use that class/file.
