### ISSUE TITLE
Rename macOS to Darwin

### ISSUE THREAD

**Issue by Gregory-Pereira** [sigstore/model-transparency#181]
**Description**

I believe that we should rename `macOS` to `Darwin`. This would make dealing with differences in platform easier, as we could just conditionally run difference in steps from `uname -s` in Bash or `platform.system()` in Python. I believe this is also more correct as `Darwin` refers to the family of OS, which makes it a more fitting counterpart to `Linux`, rather than macOS or OSX which is the implementation.

The only part of the codebase that should be unaffected are the github workflows, which leverage the `macos-latest` runner, and so can appropriately keep the `macos` naming convention.

**Comment by mihaimaruseac** [comment]
Thank you for #183, it is now merged. Should we close this? Ok to leave open if you plan further changes for this.

**Comment by Gregory-Pereira** [comment]
I think we can close this, the issue was meant to be feature specific.
