### ISSUE TITLE
Handle symlinks and excluded files in serialization

### ISSUE THREAD

**Issue by mihaimaruseac** [sigstore/model-transparency#196]
**Description**
Following #190: during migration I did not yet add support for symlinks and for excluding files. This will be handled later when we find a need for it during end-to-end testing.

**Comment by spencerschrock** [comment]
> I did not yet add support for symlinks

To clarify, I believe the code already supports symlinks as written (see #251), the TODO refers to preventing symlinks.
https://github.com/sigstore/model-transparency/blob/90e3ed354016309cb6ceca1b47bc4b8b23deb97e/model_signing/serialization/serialize_by_file_shard.py#L126-L129

This restriction was added in #24, and the only reason I can tell is from [this block](https://github.com/sigstore/model-transparency/blob/90e3ed354016309cb6ceca1b47bc4b8b23deb97e/model_signing/serialize.py#L151-L157), which reads as a TODO to potentially allow symlinks:

> To avoid bugs where we read the link rather than its target, 
we don't allow symlinks for now.
NOTE: It seems that Python's read() *always* follows symlinks,
so it may be safe to allow them. (readlink() is the function
to read the link metadata).

It would be simple to add a toggle and check for them, but is it needed? Would a signer/verifier care about the presence of a symlink?

**Comment by mihaimaruseac** [comment]
There might be an issue when the model directory has a symlink inside it that points to a file outside. If we blindly read the symlink, we won't be able to verify the model after it gets uploaded, as that file won't be sent over.

If we add a toggle to error when a symlink is found, we can detect this scenario earlier.

I don't know if there are other cases where we'd care. If the model contains a symlink to a file within itself, nothing should change

**Comment by spencerschrock** [comment]
> we won't be able to verify the model after it gets uploaded, as that file won't be sent over.

I assume this is heavily dependent on the upload process for a given model hub? My symlink knowledge is superficial at best, so I did a naive test  with `scp` from macOS -> Linux which seemed to have copied the contents.:

```shell
mkdir /tmp/foo
echo "HELLO" > /tmp/foo/bar.txt
mkdir /tmp/symlink-test
ln -s /tmp/foo/bar.txt /tmp/symlink-test/baz.txt
scp -r /tmp/symlink-test <host>:~
```

And then on the host, I see a normal file with the expected contents:
```shell
$ cat symlink-test/baz.txt 
HELLO
$ ls -laht symlink-test/baz.txt 
-rw-r--r-- 1 <me> <group> 13 Jul 23 11:48 symlink-test/baz.txt
```

> If we add a toggle to error when a symlink is found, we can detect this scenario earlier.

Sounds good. It's trivial to add the toggle, and it will be easy enough to remove if needed later.

**Comment by mihaimaruseac** [comment]
Yeah, `scp` always follows symbolic links, but other tools might not.
