### ISSUE TITLE
Automated generation of API docs

### ISSUE THREAD

**Issue by laurentsimon** [sigstore/model-transparency#209]
If there's a tool to auto-generate / update documentation based on the doc in the code, that'd be helpful.

@mihaimaruseac @spencerschrock

**Comment by spencerschrock** [comment]
Since I happened to look at sigstore's docs today, would something like their system work?

> uses [pdoc](https://github.com/mitmproxy/pdoc) to generate HTML documentation for the public Python APIs.

Which they run as part of their CI and deploy to github pages at https://sigstore.github.io/sigstore-python/sigstore.html
https://github.com/sigstore/sigstore-python/blob/f9e313eab473503ec688f5a12ed21c81ad9a81f2/.github/workflows/docs.yml

**Comment by mihaimaruseac** [comment]
This looks great! Let's do it

**Comment by spencerschrock** [comment]
There is some work towards this done in #279, but there are a few open questions still:

- [ ] Do we only want to generate new documentation for tags, or for any change to `main`
- [ ] I'm ignoring certain test files with `pdoc` CLI args, but there are other ways of ignoring files.
- [ ] Setting up the GitHub Pages and where this model_signing documentation will live, compared to any future `slsa_for_models` documentation.

**Comment by spencerschrock** [comment]
You can see an example of the documentation generated in the [action run](
https://github.com/sigstore/model-transparency/actions/runs/10289168796?pr=279) by downloading the [artifact](https://github.com/sigstore/model-transparency/actions/runs/10289168796/artifacts/1786881037).

**Comment by mihaimaruseac** [comment]
This looks good to me, thank you!

I think we might need to reorder the files in the repo as they're not in a good shape for packaging to a wheel. I'll read more about this and experiment to see if we can avoid it, otherwise we need to decide if we wait for #240 or we'd have it rebase again

**Comment by spencerschrock** [comment]
#279 has been rebased to account for the layout change in #283, and now makes use of `hatch`. 

You can see the latest [action run](https://github.com/sigstore/model-transparency/actions/runs/10394757138?pr=279) and [artifact](https://github.com/sigstore/model-transparency/actions/runs/10394757138/artifacts/1813388213) from the PR.

**Comment by spencerschrock** [comment]
https://sigstore.github.io/model-transparency
