### ISSUE TITLE
Add support for providing identity tokens obtained out-of-band

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/model-transparency#316]
**Description**

sigstore-python has support for this already, so we just need to accept an identity token via CLI or via the API and plumb the value through.

**Comment by di** [comment]
Specifically, this is the `--identity-token` flag in `sigstore-python`: https://github.com/sigstore/sigstore-python/blob/cac62e8e611d4286a49ecda7f33d356381ab7919/README.md#L149-L150

**Comment by spencerschrock** [comment]
This plumbing should also be useful for our own e2e tests if we use the token published by https://github.com/sigstore-conformance/extremely-dangerous-public-oidc-beacon for our e2e tests [discussion in the e2e issue here](https://github.com/sigstore/model-transparency/issues/5#issuecomment-1789688712).
