### ISSUE TITLE
Publish container image to sign and verify models

### ISSUE THREAD

**Issue by miyunari** [sigstore/model-transparency#328]
**Description**

The repository contains a [sign.py](https://github.com/sigstore/model-transparency/blob/2b45f9e7dc06a148ecadc08616229419252c1114/src/sign.py) and [verify.py](https://github.com/sigstore/model-transparency/blob/2b45f9e7dc06a148ecadc08616229419252c1114/src/verify.py) that can be used as standalone software. But it is not straightforward to use in a container-based environment like kubernetes.

It would be nice to release a container image that simplifies the signing and validation process in containerized environments.

To illustrate the behavior, I built a small example ([ghcr.io/miyunari/model-transparency-cli](https://github.com/users/miyunari/packages/container/package/model-transparency-cli)):
```bash
$ docker run --rm -it ghcr.io/miyunari/model-transparency-cli:latest
Usage:
  verify  - Runs the verify.py Python script
  sign    - Runs the sign.py Python script
  help    - Displays this help message

$ docker run --rm -it ghcr.io/miyunari/model-transparency-cli:latest verify
usage: Script to verify models [-h] --sig_path SIG_PATH [--model_path MODEL_PATH] {pki,private-key,sigstore,skip} ...
Script to verify models: error: the following arguments are required: --sig_path, method

$ docker run --rm -it ghcr.io/miyunari/model-transparency-cli:latest sign
usage: Script to sign models [-h] --model_path MODEL_PATH [--sig_out SIG_OUT] {pki,private-key,sigstore,skip} ...
Script to sign models: error: the following arguments are required: --model_path, method
```

Steps to fulfillment would be:
- https://github.com/sigstore/model-transparency/pull/329
- Add container build and publish step into [release workflow](https://github.com/sigstore/model-transparency/blob/2b45f9e7dc06a148ecadc08616229419252c1114/.github/workflows/release.yml).

What are your thoughts on that? :smiley:

**Comment by mihaimaruseac** [comment]
I think this is a good addition. We are planning to make `hatch` scripts that would work in similar way, maintaining the Python dependencies for you. I'll look at the PR, thank you!
