### ISSUE TITLE
MacOS speed

### ISSUE THREAD

**Issue by laurentsimon** [sigstore/model-transparency#78]
Investigate the speed on OSX. The unit tests seem to be slow. It could be because the runners are not as fast

**Comment by laurentsimon** [comment]
ah, good catch. I've assigned the issue to you.

@mihaimaruseac wrote some benchmark code in Python a while back. @mihaimaruseac would you be able to share?

**Comment by mihaimaruseac** [comment]
I will, need to clean some stuff first. It will remove the need for #182 though.

@Gregory-Pereira the issue is that the CI under `.github/workflows` is slow, not the so much benchmarking

**Comment by Gregory-Pereira** [comment]
Sounds good, ill TAL

**Comment by mihaimaruseac** [comment]
The tests are fast now with refactoring and using `hatch test` with parallelism
